// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZadanieDomowe7.Data;

#nullable disable

namespace ZadanieDomowe7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510103248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZadanieDomowe7.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU001",
                            ComponentManufacturersId = 1,
                            ComponentTypeId = 1,
                            Description = "High-end desktop processor",
                            Name = "Intel Core i9-13900K"
                        },
                        new
                        {
                            Code = "CPU002",
                            ComponentManufacturersId = 2,
                            ComponentTypeId = 1,
                            Description = "High-performance desktop CPU",
                            Name = "AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            Code = "RAM001",
                            ComponentManufacturersId = 3,
                            ComponentTypeId = 2,
                            Description = "Gaming memory module",
                            Name = "Kingston Fury 32GB DDR5"
                        },
                        new
                        {
                            Code = "RAM002",
                            ComponentManufacturersId = 4,
                            ComponentTypeId = 2,
                            Description = "Professional memory",
                            Name = "Corsair Vengeance 16GB DDR5"
                        },
                        new
                        {
                            Code = "GPU001",
                            ComponentManufacturersId = 1,
                            ComponentTypeId = 3,
                            Description = "Flagship graphics card",
                            Name = "NVIDIA RTX 4090"
                        },
                        new
                        {
                            Code = "GPU002",
                            ComponentManufacturersId = 2,
                            ComponentTypeId = 3,
                            Description = "High-end gaming GPU",
                            Name = "AMD Radeon RX 7900 XTX"
                        },
                        new
                        {
                            Code = "SSD001",
                            ComponentManufacturersId = 5,
                            ComponentTypeId = 4,
                            Description = "NVMe SSD for gaming",
                            Name = "Samsung 990 Pro 2TB"
                        },
                        new
                        {
                            Code = "SSD002",
                            ComponentManufacturersId = 4,
                            ComponentTypeId = 4,
                            Description = "Fast NVMe storage",
                            Name = "Corsair MP600 1TB"
                        },
                        new
                        {
                            Code = "PSU001",
                            ComponentManufacturersId = 4,
                            ComponentTypeId = 5,
                            Description = "Gold modular PSU",
                            Name = "Corsair RM1000e 1000W"
                        });
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Intel",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "Kingston",
                            FoundationDate = new DateTime(1987, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kingston Technology"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Corsair",
                            FoundationDate = new DateTime(1994, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair Components"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "Samsung",
                            FoundationDate = new DateTime(1969, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Samsung Electronics"
                        });
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Solid State Drive"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "PSU",
                            Name = "Power Supply Unit"
                        });
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Ultra",
                            Stock = 3,
                            Warranty = 60,
                            Weight = 15.8m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Server Standard",
                            Stock = 2,
                            Warranty = 60,
                            Weight = 20.0m
                        });
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "SSD001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "PSU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "CPU002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "SSD002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RAM001",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "GPU002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "SSD001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "CPU002",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "RAM002",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "SSD002",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.Component", b =>
                {
                    b.HasOne("ZadanieDomowe7.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZadanieDomowe7.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.PCComponent", b =>
                {
                    b.HasOne("ZadanieDomowe7.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZadanieDomowe7.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ZadanieDomowe7.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
